### ISSUE TITLE
ReloadData calls viewControllerForPageAt twice

### ISSUE THREAD

**Issue by pcentieiro** [yysskk/SwipeMenuViewController#79]
**Describe the bug**
If a SwipeMenuView is added to a ViewController (following a reloadData), or reloadData is called on the Demo project (using SwipeMenuViewController) the viewControllerForPageAt is called twice.

**To Reproduce**
1. Setup a SwipeMenuView
2. Call reloadData
3. Add a breakpoint/log on viewControllerForPageAt and you'll see being called twice per entry

**Expected behavior**

**iPhone (please complete the following information):**
 - Device: iPhone 8
 - OS: 12.1
 - Version: 3.0.0

**Comment by dks333** [comment]
Same Issue

**Comment by JhonnyTawk** [comment]
same issue.
I want to add Load more feature.
What is the alternative of `self.swipeMenuView.reloadData()` to reload TableView without reloading Tiltes and everything?

**Comment by hiromiick** [comment]
I had same issue, and could fix it. In my case, I was using SwipeMenuViewOptions. I init SwipeMenuView without options, create options, and did.swipeMenuView.reloadData(), so everything was called twice. I init SwipeMenuView with options at the first time, then all problem was solved.

**Comment by AjayOdedara** [comment]
Same issue guys,

@hiromiick  I tried to resolve with what you suggested but still getting 2 calls

**Comment by Arshad-iOSDeveloper** [comment]
Same issue for me, any solution please ?

**Comment by Arshad-iOSDeveloper** [comment]
> I had same issue, and could fix it. In my case, I was using SwipeMenuViewOptions. I init SwipeMenuView without options, create options, and did self.swipeMenuView.reloadData(options: options), so everything was called twice. I init SwipeMenuView with options at the first time, then all problem was solved.
> 
> hope it would help.

Its always better to paste the code

**Comment by Arshad-iOSDeveloper** [comment]
The problem is not with the options, it is related to reload() method. 
Even i am not able to solve the problem.
**So thinking to remove this library and use horizontal collection view for tabs**

**Comment by yysskk** [comment]
Sorry for the very late reply. The extra calls came from the content view rebuilding its pages when it was detached during a reload; this is fixed on main, so please reopen if it still happens there.
